---
title: "Fantasy 2020"
output: github_document 
---

```{r, echo=FALSE, warning=FALSE, error = FALSE, message = FALSE}
library(knitr)
source("compileleague.R")
```

####Today's auction
```{r, echo = FALSE, warning=FALSE, message = FALSE}
today <- c(
"Giovanny Gallegos",
"Keone Kela",
"Rick Porcello",
"Anthony DeSclafani",
"Gregory Polanco",
"Jon Gray",
"Dylan Bundy",
"Ender Inciarte"

) %>%
  tbl_df() %>%
  set_names("Name")


kable(left_join(today, hitterpitcher) %>%
      select(Name, marginal.total.points, dollar.value))
```

####Draft Status
```{r, echo = FALSE, warning=FALSE, message = FALSE}

#get number and average positional value for hitters
hitter_status <- hitter_projections %>% 
  filter(status != "drafted", 
         dollar.value > 1) %>% 
  group_by(position) %>% 
  summarise(remaining = n(), 
            max = max(dollar.value),
            avg = mean(dollar.value)) %>% 
  modify_at(c("avg", "max"), round, 1)

#get number and average positional value for pitchers
pitcher_status <- pitcher_projections %>% 
  filter(status != "drafted", 
         dollar.value > 1) %>% 
  summarise(remaining = n(), 
            max = max(dollar.value),
            avg = mean(dollar.value)) %>% 
  mutate(position = "pitcher") %>% 
  modify_at(c("avg", "max"), round, 1) %>% 
  select(position, remaining, max, avg)

kable(rbind(hitter_status, pitcher_status))


#get open roster spots of each time
big_team_df <- data.frame() 
all_positions <- marmaduke %>% pull(roster_spot)

for (team in teams) {big_team_df <- rbind(big_team_df, get(team))}
for (position in all_positions) {big_team_df <- add_row(big_team_df, 
                                                        roster_spot = position,
                                                        Name = "")}

#calculate number of open roster spots at each position
big_team_df <- filter(big_team_df, Name=="") %>%
  group_by(roster_spot) %>%
  summarise(remaining = n()) %>%
  spread(roster_spot, remaining) %>%
  mutate_all(function(x) x-1) %>% 
  mutate(C = C1 + C2,
         OF = OF1 + OF2 + OF3 +OF4 + OF5 + OF6,
         P = P1+P2+P3+P4+P5+P6+P7+P8+P9+P10) %>% 
  select(-(P1:P9), -(OF1:OF6), -(C1:C2)) %>% 
  gather(Position, Still_to_be_Drafted)


tot_picks <- data.frame(Position = "Total",
                        Still_to_be_Drafted=sum(big_team_df$Still_to_be_Drafted))


big_team_df <- rbind(big_team_df, tot_picks)

kable(big_team_df)

```


####Current Standings
```{r, echo = FALSE, warning=FALSE}
library(knitr)
standings <- standings.output %>% mutate(hit.points = R_points + HR_points + RBI_points + SB_points + AVG_points,
                            pitch.points = ERA_points + WHIP_points + K_points + SV_points + W_points,
                            max_bid = left - picks.left + 1) %>%
                            select(team_name, spent, left, picks.left, max_bid, total_points, hit.points,
                              pitch.points)

kable(standings)
```

####Top Remaining Pitchers
```{r, echo = FALSE}

toppitch <- filter(pitcher_projections, status != "drafted") %>%
      mutate(pts = marginal.total.points, dlr = dollar.value) %>%
      select(Name, Team, IP, ERA, WHIP, K, SV, W, pts, dlr) %>% 
      filter(row_number() < 16)

kable(toppitch)
```

####Top Remaining Hitters
```{r, echo = FALSE}
topdh <- filter(hitter_projections, status != "drafted") %>%
      mutate(pts = marginal.total.points, dlr = dollar.value) %>%
      select(Name, Team, PA, R, HR, RBI, SB, AVG, pts, dlr)  %>%
      arrange(-dlr) %>% 
      filter(row_number() < 16)

kable(topdh)
```

####Top CI
```{r, echo = FALSE}
topci <- filter(hitter_projections, status != "drafted", position %in% c("first_base","third_base")) %>% 
      mutate(pts = marginal.total.points, dlr = dollar.value) %>%
      select(Name, Team, PA, R, HR, RBI, SB, AVG, pts, dlr)  %>%
      arrange(-dlr) %>% 
      filter(row_number() < 18)

kable(topci)

```

####Top MI
```{r, echo = FALSE}
topmi <- filter(hitter_projections, status != "drafted" & position %in% c("second_base","shortstop")) %>%
      mutate(pts = marginal.total.points, dlr = dollar.value) %>%
      select(Name, Team, PA, R, HR, RBI, SB, AVG, pts, dlr)  %>%
      arrange(-dlr) %>%
      filter(row_number() <12)

kable(topmi)

```

####Top catchers
```{r, echo = FALSE}
topcatch <- filter(hitter_projections, status != "drafted", position =="catcher") %>% 
      mutate(pts = marginal.total.points, dlr = dollar.value) %>%
      select(Name, Team, PA, R, HR, RBI, SB, AVG, pts, dlr)  %>%
      arrange(-dlr) %>% 
      filter(row_number() < 12)

kable(topcatch)

```

```{r, echo = FALSE,warning=FALSE, error = FALSE, message = FALSE}
####Dollars vs. projected points
library(ggplot2)
library(ggrepel)
plot1 <- ggplot(standings.output, aes(x=spent, y=total_points)) + 
  geom_point() +
  theme_minimal() +
  xlab("Dollars Spent") +
  ylab("Projected Points")+
  geom_smooth(method = lm, se = FALSE, size = .4)+
  geom_text_repel(aes(x=spent, y=total_points, label = team_name)) 

plot1 

model <- predict(lm(total_points ~ spent, data = standings.output)) %>% 
  tbl_df() %>% 
  add_rownames() 



# delta <- select(standings.output, total_points) %>% 
#   add_rownames() %>% 
#   left_join(model) %>% 
#   mutate(delta = total_points - value) %>% 
#   arrange(-delta)
# 
# delta
```

####Remaining Picks vs. projected points
```{r, echo = FALSE,warning=FALSE, error = FALSE, message = FALSE}
library(ggplot2)
library(ggrepel)
plot <- ggplot(standings.output, aes(x=picks.left, y=total_points)) + 
  geom_point() +
  theme_minimal() +
  xlab("Remaining Picks") +
  ylab("Projected Points")+
  geom_smooth(method = lm, se = FALSE, size = .4)+
  geom_text_repel(aes(x=picks.left, y=total_points, label = team_name)) 

plot
  
```

####Best Draft Picks
```{r, echo = FALSE, warning=FALSE, error = FALSE, message = FALSE}
library(lubridate)
valuepicks <- draftpicks %>% 
  left_join(hitter_projections, by=c("player"="Name")) %>% 
  left_join(pitcher_projections, by=c("player"="Name")) %>%
  mutate(drafted=ymd(drafted)) %>% 
  filter(year(drafted)==2020) %>% 
  select(team, player, salary, dollar.value.x, dollar.value.y) %>% 
  mutate(dollar_value = pmax(dollar.value.x, dollar.value.y, na.rm=TRUE),
         equity = dollar_value - salary) %>% 
  arrange(-equity) %>% 
  select(team, player, salary, dollar_value, equity) %>% 
  filter(row_number() <21)

kable(valuepicks)
```

####Unmatched Draft Picks
```{r, echo = FALSE,warning=FALSE, error = FALSE, message = FALSE}
kable(drafterrors)
```